# -*- coding: utf-8 -*-
"""Copy of synent-task5-salesanalysis-satishjhare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mFV-N9prnFtZ4LcguTGMsfAvmlU0WCU
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("/content/drive/MyDrive/Datascience_Project /SampleSuperstore.csv")

# Display dataset
print(df.head())

# Check dataset information
print(df.info())

# Check missing values
print(df.isnull().sum())

category_sales = df.groupby('Category')['Sales'].sum()
print("\nTotal Sales by Category:")
print(category_sales)

# Bar Chart
category_sales.plot(kind='bar')

plt.title("Total Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")

plt.show()

# profit Analysis
profit_analysis = df.groupby('Category')['Profit'].sum()
print("\nProfit Analysis:")
print(profit_analysis)

# Profit Chart
profit_analysis.plot(kind='bar')

plt.title("Profit by Category")
plt.xlabel("Category")
plt.ylabel("Profit")

plt.show()

# Region Wise Sales
region_sales = df.groupby('Region')['Sales'].sum()

print("\nRegion Wise Sales:")
print(region_sales)

# Pie Chart
region_sales.plot(kind='pie', autopct='%1.1f%%')

plt.title("Region Wise Sales Distribution")
plt.ylabel("")

plt.show()

print("\nSales Data Analysis Completed Successfully")